name: Build
on:
  push:
    branches: [ "main", "actions/build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_test:
    name: Build

    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build frontend
        run: |
          cd frontend
          npm install --silent
          npm run build

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build backend
        run: |
          cargo build --release --no-default-features --features=dashboard

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-portal
          path: target/release/web-portal

      - name: Run server for simple tests
        run: |
          mkdir testing
          cp target/release/web-portal testing/
          cd testing
          ./web-portal --addr localhost:57888&

      - name: Auto update dev
        run: |
          # To do implement the update service
          # curl -i -H "Update-Secret:${{ secrets.UPDATE_SECRET }}" -X POST -F file=@target/release/web-portal https://portal.com/service/update
          

